### ISSUE TITLE
Enhancement - sample gist to get started. do you have?

### ISSUE THREAD

**Issue by johndpope** [think-dev/UIRefreshableScrollView#1]
was thinking something along the lines....

class FeedsCollectionVC: UIViewController,UICollectionViewDataSource,UICollectionViewDelegate, UICollectionViewDelegateFlowLayout{

let refresh = UIRefreshControl()
    var feedCV: UICollectionView?
    
    public init() {
       let layout: UICollectionViewFlowLayout = {
            let alayout = UICollectionViewFlowLayout.init()
            alayout.scrollDirection = .vertical
            return alayout
            
        }()
        super.init(nibName: nil, bundle:nil)
        self.feedCV = UICollectionView(frame: self.view.bounds, collectionViewLayout: layout)

        self.refresh.addTarget(self, action: #selector(FeedsCollectionVC.refreshContent), for: .valueChanged)
        self.feedCV?.addSubview(refresh)
        
        if let cv = self.feedCV{
            self.view.addSubview(cv)
        }
    }

}

**Comment by johndpope** [comment]
just read through the notes - perhaps you need a new file 

DemoReadme.md -> switch to demo brach

**Comment by johndpope** [comment]
seems like the demo branch got removed?

**Comment by think-dev** [comment]
Wow so sorry. Maybe the demo branch has been removed by mistake. I'm on holidays until next Tuesday. I'll upload a demo branch as soon as possible. I'll update this thread when it's done.

**Comment by johndpope** [comment]
sorry to bug you on holidays - always best to disconnect from emails + facebook and tv.
Enjoy your down time.

**Comment by think-dev** [comment]
No problem! I'm glad to receive comments and enhancements. Please keep watching this thread. I'll update as soon as possible

**Comment by think-dev** [comment]
Hi @johndpope! You can find an example project on this repo: 
https://github.com/think-dev/UIRefreshableScrollView-Example

Sorry for the delayed response. Please open a new issue if you experience some problem during implementation. Thank you for using UIRefreshableScrollView.
